# Generated by Django 3.1.3 on 2020-11-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='check_list',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='card',
            name='user_list',
            field=models.TextField(default=None),
        ),
    ]
