# Generated by Django 3.1.3 on 2020-11-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0005_auto_20201103_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='from_board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.board'),
        ),
    ]
