# Generated by Django 3.1.3 on 2020-11-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0007_auto_20201103_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_admin',
        ),
    ]
