# Generated by Django 3.1.3 on 2020-11-05 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0011_auto_20201105_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
