# Generated by Django 3.1.3 on 2020-11-05 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0013_auto_20201105_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 11, 10, 5, 37, 1, 446492)),
        ),
    ]
