# Generated by Django 3.1.3 on 2020-11-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0020_card_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='check_list',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='card',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='user_list',
            field=models.TextField(default=[]),
        ),
    ]
