# Generated by Django 3.1.3 on 2020-11-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0021_auto_20201107_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_address',
            field=models.CharField(default='', max_length=60),
        ),
    ]
