# Generated by Django 3.1.3 on 2020-11-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0022_fileupload_file_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file_address',
        ),
    ]
