# Generated by Django 3.1.3 on 2020-11-07 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0023_remove_fileupload_file_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='from_board',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_manager.board'),
        ),
    ]
