# Generated by Django 3.1.3 on 2020-11-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0024_auto_20201107_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AlterField(
            model_name='card',
            name='check_list',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='user_list',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(max_length=50)),
                ('role', models.CharField(default='member', max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.team')),
            ],
        ),
    ]
