# Generated by Django 3.1.3 on 2020-11-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0025_auto_20201108_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='fk_team',
        ),
    ]
