# Generated by Django 3.1.3 on 2020-11-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0026_remove_card_fk_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='check_list',
        ),
        migrations.CreateModel(
            name='CardChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=50)),
                ('checked', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.card')),
            ],
        ),
    ]
