# Generated by Django 3.1.3 on 2020-11-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0027_auto_20201108_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='user_list',
            field=models.TextField(null=True),
        ),
    ]
